//
//  LazyResolverTests.swift
//  GuiseTests
//
//  Created by Gregory Higley on 2022-09-30.
//
%{
arg_count = int(arg_count)

def args(items, fmt=lambda i: f'{i}', sep=', '):
  return sep.join(map(fmt, items))
}%

import XCTest
@testable import Guise

class LazyResolverTests: XCTestCase {
  override func setUp() {
    super.setUp()
    prepareForGuiseTests()
  }
  
  func test_sync0() throws {
    // Given
    let container: any (Resolver & Registrar) = Container()
    container.register(tags: 0) { _ in
      [] as [Int]
    }
    let lr: LazyResolver<[Int]> = try container.resolve()
   
    // When
    let ints: [Int] = try lr.resolve(tags: 0)
    
    // Then
    XCTAssertEqual(ints, [])
  }

% for a in range(1, arg_count + 1):
  func test_sync${a}() throws {
    // Given
    let container: any (Resolver & Registrar) = Container()
    container.register(tags: ${a}) { _, ${args(range(1, a + 1), lambda i: f'arg{i}')} in
      [${args(range(1, a + 1), lambda i: f'arg{i}')}] as [Int]
    }
    let lr: LazyResolver<[Int]> = try container.resolve()
   
    // When
    let ints: [Int] = try lr.resolve(tags: ${a}, args: ${args(range(0, a))})
    
    // Then
    XCTAssertEqual(ints, [${args(range(0, a))}])
  }
  
% end
  func test_resolve_sync_weak() throws {
    // Given
    var container: Container? = Container()
    container!.register(tags: "s") { _, arg in
      Service(i: arg)
    }
    let lr: LazyResolver<Service> = try container!.resolve()

    // When
    container = nil

    // Then
    do {
      _ = try lr.resolve(tags: "s", args: 7)
      XCTFail("Expected resolution to fail.")
    } catch let error as ResolutionError {
      let key = Key(Service.self, tags: "s", args: Int.self)
      guard
        error.key == key,
        case .noResolver = error.reason
      else {
        throw error
      }
    }
  }
  
  func test_async0() async throws {
    // Given
    let container: any (Resolver & Registrar) = Container()
    container.register(tags: 0) { _ async in
      [] as [Int]
    }
    let lr: LazyResolver<[Int]> = try await container.resolve()
   
    // When
    let ints: [Int] = try await lr.resolve(tags: 0)
    
    // Then
    XCTAssertEqual(ints, [])
  }

% for a in range(1, arg_count + 1):
  func test_async${a}() async throws {
    // Given
    let container: any (Resolver & Registrar) = Container()
    container.register(tags: ${a}) { _, ${args(range(1, a + 1), lambda i: f'arg{i}')} async in
      [${args(range(1, a + 1), lambda i: f'arg{i}')}] as [Int]
    }
    let lr: LazyResolver<[Int]> = try await container.resolve()
   
    // When
    let ints: [Int] = try await lr.resolve(tags: ${a}, args: ${args(range(0, a))})
    
    // Then
    XCTAssertEqual(ints, [${args(range(0, a))}])
  }
  
% end
  func test_resolve_async_weak() async throws {
    // Given
    var container: Container? = Container()
    container!.register(tags: "s") { _, arg async in
      Service(i: arg)
    }
    let lr: LazyResolver<Service> = try await container!.resolve()

    // When
    container = nil

    // Then
    do {
      _ = try await lr.resolve(tags: "s", args: 7)
      XCTFail("Expected resolution to fail.")
    } catch let error as ResolutionError {
      let key = Key(Service.self, tags: "s", args: Int.self)
      guard
        error.key == key,
        case .noResolver = error.reason
      else {
        throw error
      }
    }
  }
}

extension LazyResolverTests {
  class Service {
    let i: Int
    init(i: Int) {
      self.i = i
    }
  }
}
